import os
import django

# --- CONFIGURATION ---
# Replace 'server' with your actual project folder name if different
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'server.settings')
django.setup()

from main.models import SiteStructure

def run_import():
    master_data = [
        # BMM SITE (1-35)
        {"sr": 1, "site": "BMM", "dept": "ROLLING MILL", "desig": "RHF Operator", "skill": "HSK", "scope": 5},
        {"sr": 2, "site": "BMM", "dept": "ROLLING MILL", "desig": "Mill Tech", "skill": "HSK", "scope": 12},
        {"sr": 3, "site": "BMM", "dept": "ROLLING MILL", "desig": "Cold Shear Operator", "skill": "HSK", "scope": 7},
        {"sr": 4, "site": "BMM", "dept": "ROLLING MILL", "desig": "Mill Tech", "skill": "SK", "scope": 9},
        {"sr": 5, "site": "BMM", "dept": "ROLLING MILL", "desig": "Welder Gascutter", "skill": "SK", "scope": 4},
        {"sr": 6, "site": "BMM", "dept": "ROLLING MILL", "desig": "STACKER/Bundling Operator", "skill": "HSK", "scope": 7},
        {"sr": 7, "site": "BMM", "dept": "ROLLING MILL", "desig": "Cooling bed to Bundling Operator", "skill": "SK", "scope": 9},
        {"sr": 8, "site": "BMM", "dept": "ROLLING MILL", "desig": "EOT Crane Operator", "skill": "HSK", "scope": 14},
        {"sr": 9, "site": "BMM", "dept": "ROLLING MILL", "desig": "PRAYASHA CNC OPERATOR", "skill": "HSK", "scope": 2},
        {"sr": 10, "site": "BMM", "dept": "ROLLING MILL", "desig": "LATHE-1(AUTO & SPARK CNC)", "skill": "HSK", "scope": 2},
        {"sr": 11, "site": "BMM", "dept": "ROLLING MILL", "desig": "LATHE-2", "skill": "HSK", "scope": 2},
        {"sr": 12, "site": "BMM", "dept": "ROLLING MILL", "desig": "CNC Notching", "skill": "HSK", "scope": 1},
        {"sr": 13, "site": "BMM", "dept": "ROLLING MILL", "desig": "CNC Branding", "skill": "HSK", "scope": 2},
        {"sr": 14, "site": "BMM", "dept": "ROLLING MILL", "desig": "CNC Branding (HSK)", "skill": "HSK", "scope": 1},
        {"sr": 15, "site": "BMM", "dept": "ROLLING MILL", "desig": "SHAPPER MC", "skill": "SK", "scope": 1},
        {"sr": 16, "site": "BMM", "dept": "ROLLING MILL", "desig": "MILLING MC", "skill": "SK", "scope": 1},
        {"sr": 17, "site": "BMM", "dept": "ROLLING MILL", "desig": "Fitter ROLL ASSY", "skill": "HSK", "scope": 4},
        {"sr": 18, "site": "BMM", "dept": "ROLLING MILL", "desig": "Fitter STAND ASSY", "skill": "HSK", "scope": 4},
        {"sr": 19, "site": "BMM", "dept": "ROLLING MILL", "desig": "Guide & STAND MAINT (1)", "skill": "HSK", "scope": 1},
        {"sr": 20, "site": "BMM", "dept": "ROLLING MILL", "desig": "Guide & STAND MAINT (2)", "skill": "HSK", "scope": 2},
        {"sr": 21, "site": "BMM", "dept": "ROLLING MILL", "desig": "ASS.FITTER ROLL ASSY", "skill": "SSK", "scope": 4},
        {"sr": 22, "site": "BMM", "dept": "ROLLING MILL", "desig": "ASS.FITTER M/C SHOP", "skill": "SSK", "scope": 3},
        {"sr": 23, "site": "BMM", "dept": "ROLLING MILL", "desig": "ASS.Fitter STAND ASSY", "skill": "SSK", "scope": 2},
        {"sr": 24, "site": "BMM", "dept": "ROLLING MILL", "desig": "FITTER-MILL & HANDLING", "skill": "HSK", "scope": 10},
        {"sr": 25, "site": "BMM", "dept": "ROLLING MILL", "desig": "WELDER MILL & HANDLING", "skill": "HSK", "scope": 4},
        {"sr": 26, "site": "BMM", "dept": "ROLLING MILL", "desig": "FITTER Water Complex & EOT", "skill": "SK", "scope": 5},
        {"sr": 27, "site": "BMM", "dept": "ROLLING MILL", "desig": "WELDER ASS.FITTER WATERCOMPLEX", "skill": "SK", "scope": 3},
        {"sr": 28, "site": "BMM", "dept": "ROLLING MILL", "desig": "SR.Electrician", "skill": "HSK", "scope": 14},
        {"sr": 29, "site": "BMM", "dept": "ROLLING MILL", "desig": "Electrician", "skill": "SK", "scope": 3},
        {"sr": 30, "site": "BMM", "dept": "ROLLING MILL", "desig": "QC & Despatch", "skill": "SSK", "scope": 2},
        {"sr": 31, "site": "BMM", "dept": "UTILITY", "desig": "Pump Operator", "skill": "SSK", "scope": 6},
        {"sr": 32, "site": "BMM", "dept": "UTILITY", "desig": "Operator cum Maint Mechanical Tech", "skill": "SK", "scope": 6},
        {"sr": 33, "site": "BMM", "dept": "UTILITY", "desig": "Electrical Technician (UTILITY)", "skill": "SK", "scope": 1},
        {"sr": 34, "site": "BMM", "dept": "CNC SUPPLY", "desig": "CNC Notching (JBC)", "skill": "HSK", "scope": 10},
        {"sr": 35, "site": "BMM", "dept": "CNC SUPPLY", "desig": "CNC Branding (JBC)", "skill": "HSK", "scope": 4},

        # JAIRAJ SITE (36-60)
        {"sr": 36, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "Shift Technicians - Electrician", "skill": "SK", "scope": 5},
        {"sr": 37, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "PULPIT Operator", "skill": "SK", "scope": 3},
        {"sr": 38, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "SHIFT Technicians / Fitters", "skill": "SK", "scope": 9},
        {"sr": 39, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "Crane Operator", "skill": "SK", "scope": 6},
        {"sr": 40, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "Guide Fitter", "skill": "SK", "scope": 3},
        {"sr": 41, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "Rolling Stand Assembly Operators", "skill": "SK", "scope": 6},
        {"sr": 42, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "CNC Operator", "skill": "SK", "scope": 1},
        {"sr": 43, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "Machinist", "skill": "SK", "scope": 2},
        {"sr": 44, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "Welder & Gas Cutter", "skill": "SK", "scope": 3},
        {"sr": 45, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "TAG Assistants", "skill": "SSK", "scope": 4},
        {"sr": 46, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "Bundle Tagers", "skill": "SSK", "scope": 4},
        {"sr": 47, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "Dispatch Helpers", "skill": "SSK", "scope": 4},
        {"sr": 48, "site": "JAIRAJ", "dept": "Rolling Mill", "desig": "Technical Helpers", "skill": "SSK", "scope": 10},
        {"sr": 49, "site": "JAIRAJ", "dept": "SMS", "desig": "Shift Technicians - Electrician", "skill": "SK", "scope": 6},
        {"sr": 50, "site": "JAIRAJ", "dept": "UTILITY", "desig": "DCS Helpers", "skill": "SSK", "scope": 3},
        {"sr": 51, "site": "JAIRAJ", "dept": "UTILITY", "desig": "SMS & RM - Operators", "skill": "SK", "scope": 6},
        {"sr": 52, "site": "JAIRAJ", "dept": "UTILITY", "desig": "SMS & RM - Helpers", "skill": "SSK", "scope": 3},
        {"sr": 53, "site": "JAIRAJ", "dept": "UTILITY", "desig": "Utilities - Operators", "skill": "SK", "scope": 8},
        {"sr": 54, "site": "JAIRAJ", "dept": "UTILITY", "desig": "Utilities - Helpers", "skill": "SSK", "scope": 3},
        {"sr": 55, "site": "JAIRAJ", "dept": "UTILITY", "desig": "SMS, RM, MBF, Sinter - Welder (Crane Maint)", "skill": "SK", "scope": 5},
        {"sr": 56, "site": "JAIRAJ", "dept": "UTILITY", "desig": "Helpers - SMS, RM, MBF & Sinter", "skill": "SK", "scope": 8},
        {"sr": 57, "site": "JAIRAJ", "dept": "UTILITY", "desig": "Shift Technicians - MRSS", "skill": "SK", "scope": 6},
        {"sr": 58, "site": "JAIRAJ", "dept": "UTILITY", "desig": "Electricians - Cranes, Compressors, Pumphouse", "skill": "SK", "scope": 2},
        {"sr": 59, "site": "JAIRAJ", "dept": "UTILITY", "desig": "Technician (Pump Maintenance)", "skill": "SK", "scope": 2},
        {"sr": 60, "site": "JAIRAJ", "dept": "UTILITY", "desig": "Technician (Crane Maintenance)", "skill": "SK", "scope": 2},

        # MSSSL SITE (61-82)
        {"sr": 61, "site": "MSSSL", "dept": "BBD", "desig": "Bar to Bar Peeling", "skill": "HSK", "scope": 7},
        {"sr": 62, "site": "MSSSL", "dept": "BBD", "desig": "RM Unloading + Pointing + Shot Blasting", "skill": "SSK", "scope": 14},
        {"sr": 63, "site": "MSSSL", "dept": "BBD", "desig": "Centreless Grinding Operator", "skill": "HSK", "scope": 24},
        {"sr": 64, "site": "MSSSL", "dept": "BBD", "desig": "Straightener/Reeling M/C", "skill": "SK", "scope": 13},
        {"sr": 65, "site": "MSSSL", "dept": "BBD", "desig": "Cutting Operator - Circular Saw", "skill": "SK", "scope": 12},
        {"sr": 66, "site": "MSSSL", "dept": "BBD", "desig": "Bar to Bar (Drawing)", "skill": "HSK", "scope": 4},
        {"sr": 67, "site": "MSSSL", "dept": "BBD", "desig": "Straightening + Chamfering Operator", "skill": "SSK", "scope": 2},
        {"sr": 68, "site": "MSSSL", "dept": "BBD", "desig": "Polishing Operator", "skill": "SK", "scope": 3},
        {"sr": 69, "site": "MSSSL", "dept": "BBD", "desig": "Coil to Bar Draw Bench", "skill": "HSK", "scope": 9},
        {"sr": 70, "site": "MSSSL", "dept": "BBD/CFD/PICKLING", "desig": "Tool Room", "skill": "SK", "scope": 2},
        {"sr": 71, "site": "MSSSL", "dept": "BBD", "desig": "Crane Operator", "skill": "SK", "scope": 6},
        {"sr": 72, "site": "MSSSL", "dept": "CFD", "desig": "Coil to Coil Drawing Operator", "skill": "HSK", "scope": 11},
        {"sr": 73, "site": "MSSSL", "dept": "CFD", "desig": "Compactor + Upender Operator", "skill": "SSK", "scope": 7},
        {"sr": 74, "site": "MSSSL", "dept": "CFD", "desig": "SAPP", "skill": "SSK", "scope": 7},
        {"sr": 75, "site": "MSSSL", "dept": "CFD", "desig": "Swaging / Pointing Operator", "skill": "SK", "scope": 7},
        {"sr": 76, "site": "MSSSL", "dept": "PICKLING", "desig": "RM Unloading + Pickling & Phospating", "skill": "HSK", "scope": 10},
        {"sr": 77, "site": "MSSSL", "dept": "TSD", "desig": "ECT Helper Load/Unload/Salvage", "skill": "SSK", "scope": 4},
        {"sr": 78, "site": "MSSSL", "dept": "TSD", "desig": "UST Helper Load/Unload/Salvage", "skill": "SSK", "scope": 4},
        {"sr": 79, "site": "MSSSL", "dept": "TSD", "desig": "Sample Preparation/Testing", "skill": "SSK", "scope": 6},
        {"sr": 80, "site": "MSSSL", "dept": "HEAT TREATMENT", "desig": "STC Furnace", "skill": "SK", "scope": 11},
        {"sr": 81, "site": "MSSSL", "dept": "ELECTRICAL", "desig": "Electrical-Maintainance Supervisors", "skill": "HSK", "scope": 10},
        {"sr": 82, "site": "MSSSL", "dept": "MECHANICAL", "desig": "Mechanical-Maintainance Supervisor", "skill": "HSK", "scope": 11},

        # Arjas SITE (85-107)
        {"sr": 85, "site": "Arjas", "dept": "Rolling Mill", "desig": "Welder cum gas cutter", "skill": "SK", "scope": 3},
        {"sr": 86, "site": "Arjas", "dept": "Rolling Mill", "desig": "Bar Aligner", "skill": "SSK", "scope": 3},
        {"sr": 87, "site": "Arjas", "dept": "Rolling Mill", "desig": "Bundling M/c Operator", "skill": "SSK", "scope": 6},
        {"sr": 88, "site": "Arjas", "dept": "Rolling Mill", "desig": "Sling Man", "skill": "SSK", "scope": 3},
        {"sr": 89, "site": "Arjas", "dept": "Rolling Mill", "desig": "Tag Printer", "skill": "SSK", "scope": 3},
        {"sr": 90, "site": "Arjas", "dept": "INS- SUPPLY", "desig": "Sling Man", "skill": "SSK", "scope": 6},
        {"sr": 91, "site": "Arjas", "dept": "INS- SUPPLY", "desig": "Helper (A)", "skill": "SSK", "scope": 6},
        {"sr": 92, "site": "Arjas", "dept": "INS- SUPPLY", "desig": "Helper (B)", "skill": "SSK", "scope": 3},
        {"sr": 93, "site": "Arjas", "dept": "INS- SUPPLY", "desig": "Operator", "skill": "HSK", "scope": 6},
        {"sr": 94, "site": "Arjas", "dept": "INS- SUPPLY", "desig": "Grinder", "skill": "SSK", "scope": 12},
        {"sr": 95, "site": "Arjas", "dept": "INS- SUPPLY", "desig": "Crane Operator", "skill": "HSK", "scope": 1},
        {"sr": 96, "site": "Arjas", "dept": "INS- SUPPLY", "desig": "Helper", "skill": "USK", "scope": 3},
        {"sr": 97, "site": "Arjas", "dept": "INS- SUPPLY", "desig": "Gas Cutter", "skill": "SK", "scope": 3},
        {"sr": 98, "site": "Arjas", "dept": "INS - TONNAGE", "desig": "Dimension Checker", "skill": "HSK", "scope": 6},
        {"sr": 99, "site": "Arjas", "dept": "INS - TONNAGE", "desig": "Gas Cutter", "skill": "SK", "scope": 3},
        {"sr": 100, "site": "Arjas", "dept": "INS - TONNAGE", "desig": "Grinder", "skill": "SSK", "scope": 18},
        {"sr": 101, "site": "Arjas", "dept": "INS - TONNAGE", "desig": "Helper", "skill": "USK", "scope": 18},
        {"sr": 102, "site": "Arjas", "dept": "INS - TONNAGE", "desig": "Shift GET", "skill": "HSK", "scope": 3},
        {"sr": 103, "site": "Arjas", "dept": "Straitening", "desig": "Helper", "skill": "USK", "scope": 12},
        {"sr": 104, "site": "Arjas", "dept": "Heat Treatment", "desig": "Dimension Checker", "skill": "HSK", "scope": 2},
        {"sr": 105, "site": "Arjas", "dept": "Heat Treatment", "desig": "Grinder", "skill": "SSK", "scope": 2},
        {"sr": 106, "site": "Arjas", "dept": "Heat Treatment", "desig": "Helper", "skill": "USK", "scope": 4},
        {"sr": 107, "site": "Arjas", "dept": "Packaging", "desig": "Helper", "skill": "USK", "scope": 3},

        # SLR SITE (108-115)
        {"sr": 108, "site": "SLR", "dept": "Rolling Mill", "desig": "Mill Fitter", "skill": "HSK", "scope": 9},
        {"sr": 109, "site": "SLR", "dept": "Rolling Mill", "desig": "Roill Shop Fitter", "skill": "HSK", "scope": 6},
        {"sr": 110, "site": "SLR", "dept": "Rolling Mill", "desig": "Guide Fitter", "skill": "HSK", "scope": 2},
        {"sr": 111, "site": "SLR", "dept": "Rolling Mill", "desig": "Roll Shop Assistant Fitter", "skill": "SK", "scope": 6},
        {"sr": 112, "site": "SLR", "dept": "Rolling Mill", "desig": "Gas Cutter", "skill": "SK", "scope": 3},
        {"sr": 113, "site": "SLR", "dept": "Rolling Mill", "desig": "B H Operator", "skill": "SSK", "scope": 30},
        {"sr": 114, "site": "SLR", "dept": "Rolling Mill", "desig": "Mill Assistant Fitter", "skill": "SSK", "scope": 3},
        {"sr": 115, "site": "SLR", "dept": "Rolling Mill", "desig": "Office Boy", "skill": "USK", "scope": 1},

        # AGNI-CCM SITE (116-144)
        {"sr": 116, "site": "AGNI-CCM", "dept": "ADMIN -2", "desig": "Site Incharge / Recruitter", "skill": "HSK", "scope": 1},
        {"sr": 117, "site": "AGNI-CCM", "dept": "ADMIN -2", "desig": "Admin / Time Office", "skill": "SK", "scope": 1},
        {"sr": 118, "site": "AGNI-CCM", "dept": "FURNACE", "desig": "Melter", "skill": "HSK", "scope": 8},
        {"sr": 119, "site": "AGNI-CCM", "dept": "CCM", "desig": "Shift Incharge", "skill": "HSK", "scope": 4},
        {"sr": 120, "site": "AGNI-CCM", "dept": "CCM", "desig": "Mould Operator", "skill": "SK", "scope": 13},
        {"sr": 121, "site": "AGNI-CCM", "dept": "CCM", "desig": "Gas Cutter", "skill": "SK", "scope": 16},
        {"sr": 122, "site": "AGNI-CCM", "dept": "CCM", "desig": "SBO + Fitter", "skill": "SSK", "scope": 6},
        {"sr": 123, "site": "AGNI-CCM", "dept": "CCM", "desig": "Teemer Man", "skill": "SK", "scope": 6},
        {"sr": 124, "site": "AGNI-CCM", "dept": "CCM", "desig": "Laddle Man", "skill": "SK", "scope": 8},
        {"sr": 125, "site": "AGNI-CCM", "dept": "LADLE PREPERATION AREA", "desig": "Ladle Mason", "skill": "SSK", "scope": 4},
        {"sr": 126, "site": "AGNI-CCM", "dept": "TUNDISH PREPERATION AREA", "desig": "Tundish Mason", "skill": "SSK", "scope": 3},
        {"sr": 127, "site": "AGNI-CCM", "dept": "FORMER AREA", "desig": "Forma Fitter", "skill": "HSK", "scope": 1},
        {"sr": 128, "site": "AGNI-CCM", "dept": "FORMER AREA", "desig": "Forma Welder", "skill": "SK", "scope": 2},
        {"sr": 129, "site": "AGNI-CCM", "dept": "FORMER AREA", "desig": "Forma Helper", "skill": "USK", "scope": 2},
        {"sr": 130, "site": "AGNI-CCM", "dept": "ELECTRICAL DEPT", "desig": "Sr Electrician", "skill": "HSK", "scope": 4},
        {"sr": 131, "site": "AGNI-CCM", "dept": "ELECTRICAL DEPT", "desig": "Jr Electrician", "skill": "SK", "scope": 7},
        {"sr": 132, "site": "AGNI-CCM", "dept": "MECHANICAL DEPT", "desig": "Sr Mechanical Fitter", "skill": "HSK", "scope": 13},
        {"sr": 133, "site": "AGNI-CCM", "dept": "MECHANICAL DEPT", "desig": "Jr Mechanical Fitter", "skill": "SK", "scope": 13},
        {"sr": 134, "site": "AGNI-CCM", "dept": "LAB TECHNICIAN", "desig": "Lab Chemist", "skill": "HSK", "scope": 7},
        {"sr": 135, "site": "AGNI-CCM", "dept": "CCM -HELPERS", "desig": "Mould Operator - Helper", "skill": "USK", "scope": 4},
        {"sr": 136, "site": "AGNI-CCM", "dept": "CCM -HELPERS", "desig": "Ladle Man - Helper", "skill": "USK", "scope": 6},
        {"sr": 137, "site": "AGNI-CCM", "dept": "CCM -HELPERS", "desig": "Ladle Mason- Helper", "skill": "USK", "scope": 2},
        {"sr": 138, "site": "AGNI-CCM", "dept": "CCM -HELPERS", "desig": "Tundish Mason - Helper", "skill": "USK", "scope": 4},
        {"sr": 139, "site": "AGNI-CCM", "dept": "CCM -HELPERS", "desig": "Billet Yard - Helper", "skill": "USK", "scope": 4},
        {"sr": 140, "site": "AGNI-CCM", "dept": "CCM -HELPERS", "desig": "Lab Assistant - Helper", "skill": "USK", "scope": 2},
        {"sr": 141, "site": "AGNI-CCM", "dept": "CRANE OPERATOR", "desig": "Billet Yard", "skill": "HSK", "scope": 5},
        {"sr": 142, "site": "AGNI-CCM", "dept": "CRANE OPERATOR", "desig": "Shed -3", "skill": "HSK", "scope": 6},
        {"sr": 143, "site": "AGNI-CCM", "dept": "CRANE OPERATOR", "desig": "Shed - 4, 7, 8, 9", "skill": "HSK", "scope": 6},
        {"sr": 144, "site": "AGNI-CCM", "dept": "CRANE OPERATOR", "desig": "Shed 7, 8, 9", "skill": "HSK", "scope": 14},

        # AGNI-IF SITE (145-162)
        {"sr": 145, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-II", "desig": "Supervisor", "skill": "HSK", "scope": 2},
        {"sr": 146, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-II", "desig": "First Hand", "skill": "HSK", "scope": 2},
        {"sr": 147, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-II", "desig": "Bariman", "skill": "SK", "scope": 13},
        {"sr": 148, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-II", "desig": "Helper", "skill": "USK", "scope": 14},
        {"sr": 149, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-II", "desig": "Patching Bariman", "skill": "SK", "scope": 6},
        {"sr": 150, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-II", "desig": "Patching Helper", "skill": "USK", "scope": 5},
        {"sr": 151, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-III", "desig": "Supervisor", "skill": "HSK", "scope": 2},
        {"sr": 152, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-III", "desig": "First Hand", "skill": "HSK", "scope": 2},
        {"sr": 153, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-III", "desig": "Bariman", "skill": "SK", "scope": 13},
        {"sr": 154, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-III", "desig": "Helper", "skill": "USK", "scope": 14},
        {"sr": 155, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-III", "desig": "Patching Bariman", "skill": "SK", "scope": 6},
        {"sr": 156, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-III", "desig": "Patching Helper", "skill": "USK", "scope": 5},
        {"sr": 157, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-IV", "desig": "Supervisor", "skill": "HSK", "scope": 2},
        {"sr": 158, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-IV", "desig": "First Hand", "skill": "HSK", "scope": 2},
        {"sr": 159, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-IV", "desig": "Bariman", "skill": "SK", "scope": 13},
        {"sr": 160, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-IV", "desig": "Helper", "skill": "USK", "scope": 14},
        {"sr": 161, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-IV", "desig": "Patching Bariman", "skill": "SK", "scope": 5},
        {"sr": 162, "site": "AGNI-IF", "dept": "INDUCTION FURNACE UNIT-IV", "desig": "Patching Helper", "skill": "USK", "scope": 4},
    ]

    count = 0
    for row in master_data:
        obj, created = SiteStructure.objects.update_or_create(
            sr_no=row['sr'],
            defaults={
                'site': row['site'],
                'department': row['dept'],
                'designation': row['desig'],
                'skill_level': row['skill'],
                'scope': row['scope'],
            }
        )
        if created: count += 1

    print(f"Import complete! Added {count} new rows. Updated existing rows.")

if __name__ == "__main__":
    run_import()