# Generated by Django 5.2.7 on 2025-10-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Assistant Fitter', 'Assistant Fitter'), ('Assistant Mill Fitter', 'Assistant Mill Fitter'), ('Asst Roll Assembly Fitter', 'Asst Roll Assembly Fitter'), ('Band Saw Cutting Operator', 'Band Saw Cutting Operator'), ('Belt Polish Grinder', 'Belt Polish Grinder'), ('Bundling Dest Operator', 'Bundling Dest Operator'), ('Centerless Grinder', 'Centerless Grinder'), ('Cold Shear Operator', 'Cold Shear Operator'), ('Crane Maintenance Fitter', 'Crane Maintenance Fitter'), ('EOT Crane Operator', 'EOT Crane Operator'), ('Electrician', 'Electrician'), ('Electrical Technician', 'Electrical Technician'), ('Fabrication Fitter', 'Fabrication Fitter'), ('Finishing Mill Fitter', 'Finishing Mill Fitter'), ('Fitter', 'Fitter'), ('Furnace Operator', 'Furnace Operator'), ('Gas Cutter', 'Gas Cutter'), ('Guide Fitter', 'Guide Fitter'), ('Hydraulic Fitter', 'Hydraulic Fitter'), ('Hydraulic Operator', 'Hydraulic Operator'), ('Instrument Technician', 'Instrument Technician'), ('Jr. Electrician', 'Jr. Electrician'), ('Local Desk Operator', 'Local Desk Operator'), ('Main Pulpit Operator', 'Main Pulpit Operator'), ('Maintenance Fitter', 'Maintenance Fitter'), ('Mechanical Fitter', 'Mechanical Fitter'), ('Mill Fitter', 'Mill Fitter'), ('Peel Bar Operator', 'Peel Bar Operator'), ('Peeling Operators', 'Peeling Operators'), ('Reeling Operators', 'Reeling Operators'), ('Roll Assembly Fitter', 'Roll Assembly Fitter'), ('Roughing Mill Fitter', 'Roughing Mill Fitter'), ('Sr. Electrical Technician', 'Sr. Electrical Technician'), ('Sr. Fitter', 'Sr. Fitter'), ('Sr. Guide Fitter', 'Sr. Guide Fitter'), ('Sr. Mechanical Fitter', 'Sr. Mechanical Fitter'), ('Sr. Roll Assembly Fitter', 'Sr. Roll Assembly Fitter'), ('Stand Maintenance Fitter', 'Stand Maintenance Fitter'), ('Utility / Pump Operator', 'Utility / Pump Operator'), ('Utility Fitter', 'Utility Fitter'), ('Welder', 'Welder')], max_length=100),
        ),
    ]
