# Generated by Django 5.2.7 on 2025-10-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_role_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(help_text='Job role of the employee.', max_length=150),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='Default Company', help_text='Company the employee is being registered for.', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(help_text='Age of the employee.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Full name of the employee.', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, help_text="The employee's resume file.", null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='pending', help_text='Current status of the application.', max_length=10),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
