# Generated by Django 5.2.7 on 2025-10-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_employee_created_at_employee_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
