# Generated by Django 5.2.7 on 2025-10-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
