# Generated by Django 5.2.7 on 2025-10-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_employee_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ref_id',
            field=models.CharField(editable=False, help_text='Custom, auto-generated employee ID (e.g., BTI-1001).', max_length=20, unique=True),
        ),
    ]
