# Generated by Django 5.2.7 on 2025-10-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_employee_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='offer_letter',
            field=models.FileField(blank=True, help_text="The employee's offer letter file.", null=True, upload_to='offer_letters/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='remarks',
            field=models.TextField(blank=True, help_text="Remarks, typically for 'rejected' status.", null=True),
        ),
    ]
