# Generated by Django 5.2.7 on 2026-02-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_employee_offer_letter_employee_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('site', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('skill', models.CharField(choices=[('HSK', 'Highly Skilled'), ('SK', 'Skilled'), ('USK', 'Unskilled')], max_length=50)),
                ('scope', models.IntegerField(default=0)),
                ('present', models.IntegerField(default=0, help_text='Present count')),
                ('absent', models.IntegerField(default=0, help_text='Absent count')),
                ('weekly_off', models.IntegerField(default=0, help_text='Weekly Off count', verbose_name='W/O')),
                ('ot', models.IntegerField(default=0, help_text='Overtime', verbose_name='OT')),
                ('ff_ratio', models.CharField(blank=True, max_length=50, null=True, verbose_name='FF Ratio')),
                ('remark', models.CharField(blank=True, help_text='Daily remarks', max_length=255, null=True)),
            ],
        ),
    ]
