# Generated by Django 5.2.7 on 2026-02-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_manpowerposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('site', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('skill_level', models.CharField(max_length=10)),
                ('scope', models.IntegerField(help_text='The required manpower count')),
                ('present', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('weekly_off', models.IntegerField(default=0)),
                ('overtime', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ManpowerPosition',
        ),
    ]
