# Generated by Django 5.2.7 on 2026-02-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_manpowerentry_delete_manpowerposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerentry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
