# Generated by Django 5.2.7 on 2026-02-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_manpowerentry_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manpowerentry',
            options={'ordering': ['date', 'site', 'department']},
        ),
        migrations.AlterField(
            model_name='manpowerentry',
            name='overtime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='manpowerentry',
            name='scope',
            field=models.IntegerField(help_text='Required manpower'),
        ),
        migrations.AlterUniqueTogether(
            name='manpowerentry',
            unique_together={('date', 'site', 'department', 'designation', 'skill_level')},
        ),
    ]
