# Generated by Django 5.2.7 on 2026-02-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_manpowerentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manpowerentry',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='manpowerentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='manpowerentry',
            name='overtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manpowerentry',
            name='scope',
            field=models.IntegerField(help_text='The required manpower count'),
        ),
    ]
