# Generated by Django 5.2.7 on 2026-03-06 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_manpowerentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(unique=True)),
                ('site', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('skill_level', models.CharField(max_length=10)),
                ('scope', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Site Structure Row',
                'ordering': ['sr_no'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(default='Default Company', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ref_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='manpowerentry',
            name='scope',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manpowerentry',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sitestructure'),
        ),
    ]
